version: "3.9"
services:
  data_collector:
    build: .
    volumes:
      - /home/ubuntu/KingKong:/app/database
    command: python scripts/update_database.py

  streamlit:
    build: .
    volumes:
      - /home/ubuntu/KingKong:/app/database
    command: streamlit run apps/app.py
    ports:
      - 8501:8501
